name: Healthcheck

on:
  schedule:
    - cron: '30 11,23 * * *'
  push:
    branches:
      - main

jobs:
  check-deployment:
    runs-on: ubuntu-20.04
    steps:
      - name: Ping route /health-pipeline
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-437q.onrender.com/health-pipeline
